package neat

import (
	"cmp"
	"fmt"
	"math"
	"slices"
)

// Snapshot is a complete, serialisable record of a run in progress.
//
// Every field is exported and made of plain types, so a Snapshot round-trips
// through encoding/json without any custom marshalling. Saving one after each
// generation is enough to survive a crash on a long run.
//
// There is deliberately no random state here. A generation's randomness is
// derived from Seed and Generation, so a restored run continues exactly as the
// uninterrupted one would have.
type Snapshot struct {
	Cfg                   Config
	Seed                  uint64
	Generation            int
	Genomes               []Genome
	Species               []Species
	GenomeFitness         []float64
	BestGenome            Genome
	BestGenomeFitness     float64
	BestEverGenome        Genome
	BestEverGenomeFitness float64
	Innovations           InnovationsSnapshot
}

// InnovationsSnapshot records which historical markings have been handed out.
//
// This has to travel with the population. Restoring the genomes but not the
// registry would let a later mutation issue a marking that is already in use,
// and two different structures sharing a marking is precisely what historical
// markings exist to prevent.
type InnovationsSnapshot struct {
	CurrentID   int
	Connections []ConnectionInnovation
	Splits      []SplitInnovation
}

// ConnectionInnovation is the marking issued for a connection between two nodes.
type ConnectionInnovation struct {
	From, To int
	ID       int
}

// SplitInnovation is the set of markings issued for splitting a connection.
type SplitInnovation struct {
	ConnectionID int
	Split        Split
}

// Snapshot captures the run so it can be saved and later restored.
//
// The snapshot is safe to hold on to while the run continues. Genomes are
// never modified in place and every other slice is replaced rather than
// written to by the next generation, except the fitness slice, which is
// copied here for that reason.
//
// A population that has not been through a generation yet has no best genome,
// and records that as a fitness of -Inf, which encoding/json refuses to write.
// The snapshot stores it as zero instead, and Restore reads a zero fitness with
// no genome behind it back as "none yet".
func (p Population) Snapshot() Snapshot {
	return Snapshot{
		Cfg:                   p.Cfg,
		Seed:                  p.Seed,
		Generation:            p.Generation,
		Genomes:               p.Genomes,
		Species:               p.Species,
		GenomeFitness:         slices.Clone(p.GenomeFitness),
		BestGenome:            p.BestGenome,
		BestGenomeFitness:     serialisableFitness(p.BestGenome, p.BestGenomeFitness),
		BestEverGenome:        p.BestEverGenome,
		BestEverGenomeFitness: serialisableFitness(p.BestEverGenome, p.BestEverGenomeFitness),
		Innovations:           p.Breeder.Innovations().Snapshot(),
	}
}

func serialisableFitness(genome Genome, fitness float64) float64 {
	if genome.NumLayers() == 0 && math.IsInf(fitness, -1) {
		return 0
	}
	return fitness
}

// Restore rebuilds a population from a snapshot, ready to carry on from the
// generation it was taken at.
func Restore(snapshot Snapshot) (Population, error) {
	if err := snapshot.Cfg.Validate(); err != nil {
		return Population{}, err
	}
	if len(snapshot.Genomes) == 0 {
		return Population{}, fmt.Errorf("%w: snapshot has no genomes", ErrInvalidConfig)
	}
	for i, species := range snapshot.Species {
		for _, genomeIndex := range species.Genomes {
			if genomeIndex < 0 || genomeIndex >= len(snapshot.Genomes) {
				return Population{}, fmt.Errorf("%w: species %d refers to genome %d, which does not exist",
					ErrInvalidConfig, i, genomeIndex)
			}
		}
	}

	seed := snapshot.Seed
	if seed == 0 {
		seed = RandomSeed()
	}

	// The ID counter must be past every marking the genomes hold, or a
	// mutation after restoring would reissue one that is already in use and
	// two different structures would share a marking. A snapshot written by
	// this package satisfies that already; one that was edited, merged or
	// generated by hand may not.
	innovations := snapshot.Innovations
	innovations.CurrentID = max(innovations.CurrentID, highestGeneID(snapshot))

	pop := Population{
		Cfg:                   snapshot.Cfg,
		Seed:                  seed,
		Breeder:               NewBreeder(snapshot.Cfg, NewRand(generationSeed(seed, snapshot.Generation)), RestoreInnovations(innovations)),
		Genomes:               snapshot.Genomes,
		GenomeFitness:         snapshot.GenomeFitness,
		GenomeAdjustedFitness: make([]float64, len(snapshot.Genomes)),
		Species:               snapshot.Species,
		Generation:            snapshot.Generation,
		BestGenome:            snapshot.BestGenome,
		BestGenomeFitness:     snapshot.BestGenomeFitness,
		BestEverGenome:        snapshot.BestEverGenome,
		BestEverGenomeFitness: snapshot.BestEverGenomeFitness,
	}
	if len(pop.GenomeFitness) != len(pop.Genomes) {
		pop.GenomeFitness = make([]float64, len(pop.Genomes))
	}
	if pop.BestGenomeFitness == 0 && pop.BestGenome.NumLayers() == 0 {
		pop.BestGenomeFitness = math.Inf(-1)
	}
	if pop.BestEverGenomeFitness == 0 && pop.BestEverGenome.NumLayers() == 0 {
		pop.BestEverGenomeFitness = math.Inf(-1)
	}
	return pop, nil
}

// highestGeneID is the largest historical marking held by any genome or
// recorded in the innovation tables of a snapshot.
func highestGeneID(snapshot Snapshot) int {
	highest := 0
	genome := func(g Genome) {
		for _, layer := range g.Layers {
			for _, node := range layer {
				highest = max(highest, node.ID)
			}
		}
		for _, connection := range g.Connections {
			highest = max(highest, connection.ID)
		}
	}
	for _, g := range snapshot.Genomes {
		genome(g)
	}
	for _, species := range snapshot.Species {
		genome(species.Representative)
	}
	genome(snapshot.BestGenome)
	genome(snapshot.BestEverGenome)
	for _, connection := range snapshot.Innovations.Connections {
		highest = max(highest, connection.ID)
	}
	for _, split := range snapshot.Innovations.Splits {
		highest = max(highest, split.Split.NodeID, split.Split.InConnection, split.Split.OutConnection)
	}
	return highest
}

// Snapshot records every marking issued so far.
func (i *Innovations) Snapshot() InnovationsSnapshot {
	i.mu.Lock()
	defer i.mu.Unlock()

	snapshot := InnovationsSnapshot{
		CurrentID:   i.ids.Current(),
		Connections: make([]ConnectionInnovation, 0, len(i.connections)),
		Splits:      make([]SplitInnovation, 0, len(i.splits)),
	}
	for key, id := range i.connections {
		snapshot.Connections = append(snapshot.Connections, ConnectionInnovation{From: key.from, To: key.to, ID: id})
	}
	for connectionID, split := range i.splits {
		snapshot.Splits = append(snapshot.Splits, SplitInnovation{ConnectionID: connectionID, Split: split})
	}
	// Maps iterate in a different order every time. Sorting means two
	// snapshots of the same run serialise to the same bytes, so they can be
	// compared or deduplicated.
	slices.SortFunc(snapshot.Connections, func(a, b ConnectionInnovation) int { return cmp.Compare(a.ID, b.ID) })
	slices.SortFunc(snapshot.Splits, func(a, b SplitInnovation) int { return cmp.Compare(a.ConnectionID, b.ConnectionID) })
	return snapshot
}

// RestoreInnovations rebuilds a registry from a snapshot.
func RestoreInnovations(snapshot InnovationsSnapshot) *Innovations {
	ids := NewSequentialIDProvider()
	ids.SetCurrent(snapshot.CurrentID)
	innovations := NewInnovations(ids)
	for _, connection := range snapshot.Connections {
		innovations.connections[connectionKey{from: connection.From, to: connection.To}] = connection.ID
	}
	for _, split := range snapshot.Splits {
		innovations.splits[split.ConnectionID] = split.Split
	}
	return innovations
}
